name: yt_filter_kids
description: A YouTube filter app for kids with parental controls
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.1.4
  google_mobile_ads: ^6.0.0
  intl: ^0.20.2
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.2.2
  share_plus: ^11.0.0
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.9.1
  xml: ^6.5.0  # Using Flutter SDK compatible version
  youtube_player_flutter: ^9.1.2
  cached_network_image: ^3.3.1
  provider: ^6.1.5
  go_router: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
